export const FILL_IN = 'Это поле обязательно для заполнения';
export const INVALID_EMAIL_INPUT = 'Некорректный формат электронной почты';
export const INVALID_PHONE_INPUT = 'Некорректный формат номера телефона. Ожидаемый формат: +7 (xxx) xxx-xx-xx';
export const MIN_6_LENGTH = 'Минимальная длина 6 символов';
export const MAX_30_LENGTH = 'Максимальная длина 30 символов';
export const LOGIN_FAILED = 'Не удалось войти в аккаунт';
export const LOGIN_SUCCESSED = 'Авторизация прошла успешно';
export const REGISTRATION_FAILED = 'Произошла ошибка при регистрации';
export const REGISTRATION_SUCCESSED = 'Регистрация прошла успешно';
export const AT_LEAST_A_DIGIT = 'Пароль должен содержать хотя бы одну цифру'